### ISSUE TITLE
Upgrade flow-script to 0.7.10

### ISSUE THREAD

**Issue by klangner** [carldata/face-formula-converter#5]
This version correctly handles FACE script with constant value.

**Comment by wenta** [comment]
test(looks fine):
``
$ curl -H "Content-Type: application/json" -X POST -d '1' localhost:8080/api/convert
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    79  100    78  100     1   4875     62 --:--:-- --:--:-- --:--:--  4875
def f(x: Number):Number = 1.0

def main(x: TimeSeries):TimeSeries = map(x,f)
